name: "Makefiles"

on:
  push:
  pull_request:

jobs:
  download-remote:
    name: "Test remote Makefile download"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create test directory
        run: |
          mkdir -p ./test-download
          cp -a Makefile ./test-download
          cp -a .env ./test-download
      - name: Run make command
        run: |
          cd ./test-download
          make

  terraform:
    name: "Unit Tests for Terraform"
    runs-on: ubuntu-18.04
    env:
      working-directory: ./examples/terraform/local-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Test
        id: test
        run: make test
        working-directory: ${{env.working-directory}}
