name: "Makefiles"

on:
  push:
  pull_request:

jobs:
  terraform:
    name: "Unit Tests for Terraform"
    runs-on: ubuntu-18.04
    env:
      working-directory: ./examples/terraform/local-backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Test
        id: test
        run: make test
        working-directory: ${{env.working-directory}}
